apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpapp
  namespace: wr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: phpwr.kdvops.com
    external-dns.alpha.kubernetes.io/ttl: "120"
    external-dns.alpha.kubernetes.io/target: "silencfox.duckdns.org"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: phpwr.kdvops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: php-service
            port:
              number: 30080
  tls:
  - hosts:
    - phpwr.kdvops.com
    secretName: phpwr-kdvops-com-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin
  namespace: wr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: phpmyadminwr.kdvops.com
    external-dns.alpha.kubernetes.io/ttl: "120"
    external-dns.alpha.kubernetes.io/target: "silencfox.duckdns.org"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: phpmyadminwr.kdvops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phpmyadmin
            port:
              number: 30081
  tls:
  - hosts:
    - phpmyadminwr.kdvops.com
    secretName: phpmyadminwr-kdvops-com-tls
